### PR TITLE
Updating operator's documentation

### PR DESCRIPTION
**Pull request by varad-ahirwadkar**
Updating the description of the Operator

### CODE REVIEW

**Comment by varad-ahirwadkar** [comment]
Hi @mkumatag, Currently we have specified the `OpenShift Optional` category for the operator. Here is the list of categories [categories.json](https://github.com/operator-framework/community-operators/blob/master/categories.json).  Could you please let me know the most suitable category? Thanks!

**Comment by mkumatag** [comment]
> Hi @mkumatag, Currently we have specified the `OpenShift Optional` category for the operator. Here is the list of categories [categories.json](https://github.com/operator-framework/community-operators/blob/master/categories.json). Could you please let me know the most suitable category? Thanks!

how about `Monitoring`?

**Comment by varad-ahirwadkar** [comment]
Hi @mkumatag, could you please review this PR? Thanks

**Review by mkumatag — APPROVED** [review]
/lgtm

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
